add app-api deploy + api reachable test

diff --git a/hack/k8s/tests.yaml b/hack/k8s/tests.yaml
--- a/hack/k8s/tests.yaml
+++ b/hack/k8s/tests.yaml
@@ -55,6 +55,89 @@ spec:
       restartPolicy: Never
 
 
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: check-app-api
+spec:
+  backoffLimit: 0
+  template:
+    metadata:
+      labels:
+        app: check-app-api
+    spec:
+      containers:
+      - name: tests
+        image: tests-tilt-ref
+        env:
+          - name: POSTGRES_HOST
+            value: postgres
+          - name: POSTGRES_PORT
+            value: "5432"
+          - name: POSTGRES_USER
+            value: root
+          - name: PGPASSWORD
+            value: root
+          - name: POSTGRES_DB
+            value: rootdb
+          - name: APP_API_HOST
+            value: app-api
+          - name: APP_API_PORT
+            value: "80"
+        command:
+        - ash
+        - -c
+        - |
+          set -o errexit
+          set -o nounset
+          # set -o xtrace
+
+          if set +o | grep -F 'set +o pipefail' > /dev/null; then
+            # shellcheck disable=SC3040
+            set -o pipefail
+          fi
+
+          if set +o | grep -F 'set +o posix' > /dev/null; then
+            # shellcheck disable=SC3040
+            set -o posix
+          fi
+
+          echo wait for api ready
+          #timeout 60 sh -c "while ! (curl --max-time 1 -s --fail -o /dev/null ${APP_API_HOST}:${APP_API_PORT}/api/v1/health); do printf '%s' '.'; sleep 1; done;"
+          #timeout 120 sh -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${APP_API_HOST}:${APP_API_PORT}/api/v1/health)" != "200" ]]; do sleep 5; done' || false
+
+          #export API_URL=${APP_API_HOST}:${APP_API_PORT}/api/v1/health
+          #export STATUS=200
+          #while [[ "${STATUS_RECEIVED:-}" != "${STATUS}" ]]; do
+          #    STATUS_RECEIVED=$(curl --max-time 1 -s -o /dev/null -L -w ''%{http_code}'' ${API_URL} || true);
+          #    echo "received status: $STATUS_RECEIVED";
+          #    sleep 1;
+          #done;
+
+          func_curl_check_endpoint() {
+            TEST_ENDPOINT=${1:-http://localhost:80/healthz}
+
+            echo "test endpoint: ${TEST_ENDPOINT}"
+            curl -v --fail --silent -o /dev/null -X 'GET' \
+              --connect-timeout 1 \
+              --max-time 5 \
+              --retry 60 \
+              --retry-delay 1 \
+              --retry-max-time 120 \
+              "${TEST_ENDPOINT}" \
+              -H 'accept: application/json'
+          }
+
+          func_curl_check_endpoint "http://${APP_API_HOST}:${APP_API_PORT}/api/v1/health"
+
+          echo api reachable/healthy
+
+          # === test api ======================================================
+
+          echo done;
+      restartPolicy: Never
+
 # ---
 # apiVersion: batch/v1
 # kind: Job
