add api newman tests k8s & tilt setup

diff --git a/hack/k8s/tests.yaml b/hack/k8s/tests.yaml
--- a/hack/k8s/tests.yaml
+++ b/hack/k8s/tests.yaml
@@ -138,6 +138,133 @@ spec:
           echo done;
       restartPolicy: Never
 
+
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: check-app-api-newman
+spec:
+  backoffLimit: 0
+  template:
+    metadata:
+      labels:
+        app: check-app-api-newman
+    spec:
+      initContainers:
+        - name: tests
+          image: tests-tilt-ref
+          env:
+            - name: APP_API_HOST
+              value: app-api
+            - name: APP_API_PORT
+              value: "80"
+            - name: API_PATH
+              value: /api/v1
+          command:
+            - ash
+            - -c
+            - |
+              set -o errexit
+              set -o nounset
+              # set -o xtrace
+
+              if set +o | grep -F 'set +o pipefail' > /dev/null; then
+                # shellcheck disable=SC3040
+                set -o pipefail
+              fi
+
+              if set +o | grep -F 'set +o posix' > /dev/null; then
+                # shellcheck disable=SC3040
+                set -o posix
+              fi
+
+              export APIURL=http://${APP_API_HOST}:${APP_API_PORT}${API_PATH}
+
+              func_curl_check_endpoint() {
+                TEST_ENDPOINT=${1:-http://localhost:80/healthz}
+
+                echo "test endpoint: ${TEST_ENDPOINT}"
+                curl -v --fail --silent -o /dev/null -X 'GET' \
+                  --connect-timeout 1 \
+                  --max-time 5 \
+                  --retry 60 \
+                  --retry-delay 1 \
+                  --retry-max-time 120 \
+                  "${TEST_ENDPOINT}" \
+                  -H 'accept: application/json'
+              }
+
+              func_curl_check_endpoint "${APIURL}/health"
+
+              echo api reachable/healthy
+
+              # === api create user ======================================================
+
+              REGISTRATION_JSON=$(cat <<END_HEREDOC
+              {
+                "user":{
+                  "username": "Jacob",
+                  "email": "jake@jake.jake",
+                  "password": "jakejake"
+                }
+              }
+              END_HEREDOC
+              )
+
+              printf 'REGISTRATION_JSON:\n%s\n' "${REGISTRATION_JSON}"
+
+              # allowed to fail (not perfect but atm easiest way for user-already-exist kind of check)
+              curl -v --header "Content-Type: application/json" \
+                --request POST \
+                --data "${REGISTRATION_JSON}" \
+                "${APIURL}/users"
+
+              echo ""
+
+              echo done;
+      containers:
+        - name: test-api-newman
+          image: tests-api-newman-tilt-ref
+          env:
+            - name: APP_API_HOST
+              value: app-api
+            - name: APP_API_PORT
+              value: "80"
+            - name: API_PATH
+              value: /api/v1
+            # - name: USERNAME
+            #   value: Jacob
+            # - name: EMAIL
+            #   value: jake@jake.jake
+            # - name: PASSWORD
+            #   value: jakejake
+          command:
+            - ash
+            - -c
+            - |
+              set -o errexit
+              set -o nounset
+              # set -o xtrace
+
+              if set +o | grep -F 'set +o pipefail' > /dev/null; then
+                # shellcheck disable=SC3040
+                set -o pipefail
+              fi
+
+              if set +o | grep -F 'set +o posix' > /dev/null; then
+                # shellcheck disable=SC3040
+                set -o posix
+              fi
+
+              export APIURL=http://${APP_API_HOST}:${APP_API_PORT}${API_PATH}
+
+              cd /api && ./run-api-tests.sh
+
+              echo done
+      restartPolicy: Never
+
+
 # ---
 # apiVersion: batch/v1
 # kind: Job
